### ISSUE TITLE
MudSelectExtended - Could not find 'mudScrollManagerExtended.scrollToMiddle' ('mudScrollManagerExtended' was undefined).

### ISSUE THREAD

**Issue by pandapknaepel** [CodeBeamOrg/CodeBeam.MudExtensions#147]
Hi, i get an exception when re-open the MudSelectExtended with an value selected.

**Implementation**
~~~c#
<MudSelectExtended
    Class="mb-3"
    T="Clients.Models.DataAccess.PromptTemplate"
    ValueChanged="SelectedTemplateChanged"
    Label="@StringLocalizer["PromptTemplate"]"
    ItemCollection="_promptTemplates"
    ToStringFunc="@(t => t?.Name)"
    SearchBox="true"
    SearchBoxAutoFocus="true"/>
~~~

**Exception**
~~~
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not find 'mudScrollManagerExtended.scrollToMiddle' ('mudScrollManagerExtended' was undefined).
      Error: Could not find 'mudScrollManagerExtended.scrollToMiddle' ('mudScrollManagerExtended' was undefined).
          at http://localhost:5219/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at s.findFunction (http://localhost:5219/_framework/blazor.server.js:1:465)
          at E (http://localhost:5219/_framework/blazor.server.js:1:2611)
          at http://localhost:5219/_framework/blazor.server.js:1:3499
          at new Promise (<anonymous>)
          at Ft.beginInvokeJSFromDotNet (http://localhost:5219/_framework/blazor.server.js:1:3480)
          at Ft._invokeClientMethod (http://localhost:5219/_framework/blazor.server.js:1:75066)
          at Ft._processIncomingData (http://localhost:5219/_framework/blazor.server.js:1:72690)
          at Ft.connection.onreceive (http://localhost:5219/_framework/blazor.server.js:1:67003)
      Microsoft.JSInterop.JSException: Could not find 'mudScrollManagerExtended.scrollToMiddle' ('mudScrollManagerExtended' was undefined).
      Error: Could not find 'mudScrollManagerExtended.scrollToMiddle' ('mudScrollManagerExtended' was undefined).
          at http://localhost:5219/_framework/blazor.server.js:1:497
          at Array.forEach (<anonymous>)
          at s.findFunction (http://localhost:5219/_framework/blazor.server.js:1:465)
          at E (http://localhost:5219/_framework/blazor.server.js:1:2611)
          at http://localhost:5219/_framework/blazor.server.js:1:3499
          at new Promise (<anonymous>)
          at Ft.beginInvokeJSFromDotNet (http://localhost:5219/_framework/blazor.server.js:1:3480)
          at Ft._invokeClientMethod (http://localhost:5219/_framework/blazor.server.js:1:75066)
          at Ft._processIncomingData (http://localhost:5219/_framework/blazor.server.js:1:72690)
          at Ft.connection.onreceive (http://localhost:5219/_framework/blazor.server.js:1:67003)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at MudExtensions.MudListExtended`1.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
~~~

**[Video](https://schicks.digital/download/f16b71f0-1ab2-4919-902c-286057c9f3fa#22NRLs2B1AqEH3Rg5L4euF3aQ907VnjN2Hw1kSCbvqg%3D)**

**Comment by mckaragoz** [comment]
Hi, the component is working on docs.

Did you add the script `<script src="_content/CodeBeam.MudBlazor.Extensions/MudExtensions.min.js"></script>` which defined on installation steps in readme?

And if you upgrade your package, please check the script src, its changed.

If it still doesn't work after adding script properly, press Ctrl + f5 to force reload.

**Comment by pandapknaepel** [comment]
Ah, thanks. It was the old scr `<script src="_content/CodeBeam.MudExtensions/MudExtensions.js"></script>.`

**Comment by mckaragoz** [comment]
And please don't forget, the package moved on https://www.nuget.org/packages/CodeBeam.MudBlazor.Extensions 🙂
