### ISSUE TITLE
Bug in MudSpeedDial 

### ISSUE THREAD

**Issue by IngoManthey** [CodeBeamOrg/CodeBeam.MudExtensions#16]
After the update from 6.0.3  to 6.0.4, the following error appears on all pages on which I use MudSpeedDial:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Failed to execute 'setAttribute' on 'Element': '@onmouseenter' is not a valid attribute name.
      Error: Failed to execute 'setAttribute' on 'Element': '@onmouseenter' is not a valid attribute name.
          at se.applyAttribute (https://localhost:44392/_framework/blazor.webassembly.js:1:24602)
          at se.insertElement (https://localhost:44392/_framework/blazor.webassembly.js:1:23561)
          at se.insertFrame (https://localhost:44392/_framework/blazor.webassembly.js:1:22545)
          at se.applyEdits (https://localhost:44392/_framework/blazor.webassembly.js:1:21177)
          at se.updateComponent (https://localhost:44392/_framework/blazor.webassembly.js:1:20461)
          at https://localhost:44392/_framework/blazor.webassembly.js:1:57076
          at At.Fe._internal.renderBatch (https://localhost:44392/_framework/blazor.webassembly.js:1:57448)
          at Object.St [as invokeJSFromDotNet] (https://localhost:44392/_framework/blazor.webassembly.js:1:60134)
          at _mono_wasm_invoke_js_blazor (https://localhost:44392/_framework/dotnet.6.0.10.t0ikues7qu.js:1:195300)
          at wasm://wasm/00971d2a:wasm-function[3308]:0xc6102

**Comment by mckaragoz** [comment]
Yes you are right. With .net 7 preperations MudBlazor has little changes for onmouseenter and onmouseleave events. Will fix it with next release.
