### ISSUE TITLE
SignaturePad - Failed to execute 'drawImage' on 'CanvasRenderingContext2D':

### ISSUE THREAD

**Issue by arizvi-techgies** [CodeBeamOrg/CodeBeam.MudExtensions#340]
MudExtensions.min.js:1  Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at MudSignaturePad.drawLine (http://localhost:5072/_content/CodeBeam.MudBlazor.Extensions/MudExtensions.min.js:1:4064)
    at HTMLCanvasElement.<anonymous> (http://localhost:5072/_content/CodeBeam.MudBlazor.Extensions/MudExtensions.min.js:1:1944)

**Comment by mckaragoz** [comment]
Could you give some more info? Only on mobile or also desktop?

**Comment by arizvi-techgies** [comment]
It's on both; I have checked everything., and matched it with the examples, but I have the same error. Because I had to deliver my product, I removed that and used jQuery lib for signaturePad. (which I don't wanted to, but no choice left)

**Comment by mckaragoz** [comment]
There should be no issues now. Please check installation guide again, you need to install js file which described in readme. If you still have problems please re-open this issue.
