### ISSUE TITLE
MudSelectExtended with JSException.

### ISSUE THREAD

**Issue by yangf85** [CodeBeamOrg/CodeBeam.MudExtensions#370]
Title: Style Issues and JavaScript Errors with MudSelectExtended Component

Body:

Description
I am encountering an issue with the MudSelectExtended component in my Blazor application. The component’s styling appears incorrect, and it throws a JavaScript exception after a single selection.
Code
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/42733580/3abe895a-f392-4f96-93f2-363f2a7d377d)
UI
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/42733580/a5e278d0-afb0-419e-87b7-26dcccc90d0e)

Exception
blazor.web.js:1  [2024-04-13T13:20:03.972Z] Error: Microsoft.JSInterop.JSException: Could not find 'mudScrollManagerExtended.scrollToMiddle' ('mudScrollManagerExtended' was undefined).
Error: Could not find 'mudScrollManagerExtended.scrollToMiddle' ('mudScrollManagerExtended' was undefined).
    at https://localhost:7266/_framework/blazor.web.js:1:734
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:7266/_framework/blazor.web.js:1:702)
    at b (https://localhost:7266/_framework/blazor.web.js:1:5445)
    at https://localhost:7266/_framework/blazor.web.js:1:3238
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7266/_framework/blazor.web.js:1:3201)
    at gn._invokeClientMethod (https://localhost:7266/_framework/blazor.web.js:1:62841)
    at gn._processIncomingData (https://localhost:7266/_framework/blazor.web.js:1:60316)
    at connection.onreceive (https://localhost:7266/_framework/blazor.web.js:1:53957)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at MudExtensions.MudListExtended`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by mckaragoz** [comment]
It look like you didn't install MudExtensions packages properly. Please look at Readme for installation instructions. Need to add script and css files.

**Comment by yangf85** [comment]
> 看起来您没有正确安装 MudExtensions 软件包。有关安装说明，请查看自述文件。需要添加脚本和css文件。

thanks, i will try it

**Comment by yangf85** [comment]
> It look like you didn't install MudExtensions packages properly. Please look at Readme for installation instructions. Need to add script and css files.


Now there’s a new problem: when I bind a value, I can’t switch selections. Is there something wrong with the settings?
![recording](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/42733580/87099203-856b-4c4e-b4e3-dd1078bbbb05)


Code
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/42733580/99f69732-83cf-4f16-9ca1-db47065baf50)
![image](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/42733580/34fae716-5392-44a4-ade4-506a7cf5a64b)

**Comment by thatplatypus** [comment]
I also had this issue in a project of mine recently. I'm not sure why, but the script from the Codebeam package wasn't being copied in with the other packages to the _content correctly. Couldn't figure out why but had to move on so just manually stuffed the MudExtensions.min.css in my client project's wwwroot and it resolved it.

.Net 8 webassembly

**Comment by mckaragoz** [comment]
We are closing this issue, because it look like cache refresh problem. Please reopen it or open a new issue if you have other build errors.
