### ISSUE TITLE
MudSelectExtended not working

### ISSUE THREAD

**Issue by tantuffah** [CodeBeamOrg/CodeBeam.MudExtensions#454]
Hi,
I'm trying to use this library but I have some problem with MudSelectExtended components.

My projects has:
MudBlazor 7.7.0
CodeBeam.MudBlazor.Extensions 7.0.1
.NET 8

When I try to use this component I get this error:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.StringBuilderCache.GetStringAndRelease(StringBuilder sb)
   at MudBlazor.Utilities.StyleBuilder.Build()
   at MudExtensions.MudListExtended`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Stylename()
   at MudExtensions.MudListExtended`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```
My code is:
```
    <MudSelectExtended T="string" @bind-Value="@model.SenderFilterStr"
                       For="@(() => model.SenderFilterStr)"
                       Margin="Margin.Dense"
                       Dense="true"
                       FullWidth="true">
        @if (senderOpts != null)
        {
            @foreach (var opt in senderOpts)
            {
                <MudSelectItemExtended Value="opt.Id" T="string" >
                    @opt.Value
                </MudSelectItemExtended>
            }
        }
    </MudSelectExtended>
```
where senderOpts is just a List of object (Id, Value) that is calculate asynchronously.

I also tried trymudextensions.pages.dev, using same code found on  https://codebeam-mudextensions.pages.dev/mudselectextended (first example):
```
<div class="d-flex gap-8">
    <MudSelectExtended T="string" Label="RenderFragment Based">
        <MudSelectItemExtended Value="@("Foo")" Text="Foo" />
        <MudSelectItemExtended Value="@("Bar")" Text="Bar" />
        <MudSelectItemExtended Value="@("Fizz")" Text="Fizz" />
        <MudSelectItemExtended Value="@("Buzz")" Text="Buzz" />
    </MudSelectExtended>

    <MudSelectExtended T="string" Label="Data Based" ItemCollection="_collection" />
</div>

@code {
    string[] _collection = new string[] { "Foo", "Bar", "Fizz", "Buzz" };
}
```
but it has problems too: the dropdown with list is not shown.

(Dont know why, but I cannot save snipet on trymudextensions.pages.dev - save icon is disabled -, so I cannot post link to a code ready to test).

May you please help me?

**Comment by SpikeThatMike** [comment]
I had a similar issue, downgrading to Mudblazor 7.6.0 fixed it for now

**Comment by tantuffah** [comment]
Thanks! Now it works.

**Comment by TrixxTraxx** [comment]
Same issue here, downgrading Mudblazor works tho.

**Comment by ziomek64** [comment]
Similar issue on MudTextM3. 7.6 works

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at System.Text.StringBuilderCache.GetStringAndRelease(StringBuilder sb)
         at MudBlazor.Utilities.StyleBuilder.Build()
         at MudExtensions.MudTextM3.get_StyleString()
         at MudExtensions.MudTextM3.BuildRenderTree(RenderTreeBuilder __builder)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'IUR1aZChmmjaQlOCFqqrnsZgmCMsbjFQmpavLtA9igg'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at System.Text.StringBuilderCache.GetStringAndRelease(StringBuilder sb)
         at MudBlazor.Utilities.StyleBuilder.Build()
         at MudExtensions.MudTextM3.get_StyleString()
         at MudExtensions.MudTextM3.BuildRenderTree(RenderTreeBuilder __builder)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by mckaragoz** [comment]
Approved that we have compatibility issue with latest (7.7.0) core version. Will release a compatible one as soon as possible.

**Comment by Soulfire86** [comment]
This seems to be fine now with MudBlazor v7.8.0 just released.
Was this issue I believe: https://github.com/MudBlazor/MudBlazor/pull/9765

**Comment by ziomek64** [comment]
> This seems to be fine now with MudBlazor v7.8.0 just released.
> Was this issue I believe: https://github.com/MudBlazor/MudBlazor/pull/9765

So it wasn't extensions at fault?

**Comment by ScarletKuro** [comment]
Fixed with v7.8.0 MudBlazor

> So it wasn't extensions at fault?

It wasn't. One of the community PRs broke the API. Tho if the `CodeBeam.MudBlazor.Extensions` was recompiled with against the new version, it would fix the problem as well.

**Comment by moosewall** [comment]
I just updated to **MudBlazor v7.9.0** and my **CodeBeam.MudBlazor.Extensions v7.0.1 MudSelectedExtended** control stopped working.  It shows the exception below.

I downgraded to **MudBlazor v7.8.0** like suggested in this thread (THANKS!) and it works again.


*)  Exception thrown at time of control failure:
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Method not found: 'Void MudBlazor.Services.KeyInterceptorOptions.set_TargetClass(System.String)'.

System.MissingMethodException: Method not found: 'Void MudBlazor.Services.KeyInterceptorOptions.set_TargetClass(System.String)'.
   at MudExtensions.MudSelectExtended`1.OnAfterRenderAsync(Boolean firstRender)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at MudExtensions.MudSelectExtended`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync()

**Comment by ScarletKuro** [comment]
> *) Exception thrown at time of control failure: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Method not found: 'Void MudBlazor.Services.KeyInterceptorOptions.set_TargetClass(System.String)'.
> 
> System.MissingMethodException: Method not found: 'Void MudBlazor.Services.KeyInterceptorOptions.set_TargetClass(System.String)'. at MudExtensions.MudSelectExtended`1.OnAfterRenderAsync(Boolean firstRender) at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at MudExtensions.MudSelectExtended`1.OnAfterRenderAsync(Boolean firstRender) at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync()

Ah, another accidental break: https://github.com/MudBlazor/MudBlazor/pull/9896#issuecomment-2407618246

**Comment by ScarletKuro** [comment]
> Ah, another accidental break: [MudBlazor/MudBlazor#9896 (comment)](https://github.com/MudBlazor/MudBlazor/pull/9896#issuecomment-2407618246)

Pushed v7.10.0 https://www.nuget.org/packages/MudBlazor/7.10.0
Can you verify it's working now? @moosewall

**Comment by moosewall** [comment]
I just updated to **MudBlazor v7.10.0** and the CodeBeam.MudBlazor.Extensions v7.0.1 **MudSelectedExtended** control works again.  THANKS @ScarletKuro !!!!!! :-)
