### ISSUE TITLE
MudStepperExtended Inverted Parameters

### ISSUE THREAD

**Issue by meingott2** [CodeBeamOrg/CodeBeam.MudExtensions#463]
There is a problem with the inverted parameters in MudStepperExtended. We have set the parameter DisableAnimation="true" to Animation="false" and get an error message from the animator. If we set Animation="true" everything works. The description has obviously not been updated yet. Does this also affect other inverted parameters?

**Comment by mckaragoz** [comment]
What kind of error message do you get? We changed only `DisableSomething` to `EnableSomething` or only `Something`. It's the same with MudBlazor core.

**Comment by e0548965** [comment]
Having the same issue I think. Using version 8.0.0.

If we set Animation="true" the component work (although we do not want the animation)

If we set Animation="false" we get the following error consistently:

```
Fail: Microsoft.AspNetCore.Components.Web.ErrorBoundary[0]
      System.InvalidOperationException: The render handle is not yet assigned.
         at Microsoft.AspNetCore.Components.RenderHandle.ThrowNotInitialized()
         at Microsoft.AspNetCore.Components.RenderHandle.get_Dispatcher()
         at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Action workItem)
         at MudExtensions.MudAnimate.Refresh()
         at MudExtensions.MudStepperExtended.SetActiveStepByIndex(Int32 index, Boolean firstCompleted, Boolean skipPreventProcess)
         at MudExtensions.MudStepperExtended.SetActiveIndex(MudStepExtended step, Boolean skipPreventProcess)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
System.InvalidOperationException: The render handle is not yet assigned.
   at Microsoft.AspNetCore.Components.RenderHandle.ThrowNotInitialized()
   at Microsoft.AspNetCore.Components.RenderHandle.get_Dispatcher()
   at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Action workItem)
   at MudExtensions.MudAnimate.Refresh()
   at MudExtensions.MudStepperExtended.SetActiveStepByIndex(Int32 index, Boolean firstCompleted, Boolean skipPreventProcess)
   at MudExtensions.MudStepperExtended.SetActiveIndex(MudStepExtended step, Boolean skipPreventProcess)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by e0548965** [comment]
Any thoughts on this @mckaragoz ?

**Comment by mckaragoz** [comment]
That was an easy mistake, it tried to communicate MudAnimate that didn't exist. The fix will be available on next release.
